version: '3'
services:
  nextjs-app:
    build: .
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container
      - /usr/src/app/node_modules  # Keep node_modules inside the container
    command: npm run dev  # Command to start the Next.js app
