import localFont from "next/font/local";
import "./globals.css";
import clsx from "clsx";
import FirefliesBackground from "@/app/components/FirefliesBackground";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Portfolio with 3D models",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx('bg-background text-foreground ',)}
      >
        {children}
        <FirefliesBackground/>
      </body>
    </html>
  );
}
